
  name: flashlight_app
  description: A simple flashlight app with timer and SOS features.
  publish_to: 'none'
  version: 1.0.0+1

  environment:
    sdk: ">=2.17.0 <3.0.0"

  dependencies:
    flutter:
      sdk: flutter
    torch_light: ^1.0.0
    cupertino_icons: ^1.0.2

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^2.0.0

  flutter:
    uses-material-design: true